kind: ClusterTask
apiVersion: tekton.dev/v1beta1
metadata:
  name: add-revision-label
spec:
  params:
    - name: APP_NAME
      type: string
    - name: GIT_REVISION
      type: string
    - name: GIT_BRANCH_REF
      type: string
    - name: RESOURCE
      type: string
  steps:
    - name: tag-image
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash

        set -x

        IFS="/" read -a branchref <<< "$(params.GIT_BRANCH_REF)"
        BRANCH="${branchref[-1]}"
        NAMESPACE="$(params.APP_NAME)-$BRANCH"

        #!/usr/bin/env bash

        echo "adding label to deployment config $(params.APP_NAME)"

        oc label $(params.RESOURCE) $(params.APP_NAME) rev=$(params.GIT_REVISION) --overwrite -n $NAMESPACE
