kind: ClusterTask
apiVersion: tekton.dev/v1beta1
metadata:
  name: argocd-sync-app
spec:
  params:
    - description: name of the application to sync
      name: APP_NAME
      type: string
    - name: GIT_BRANCH_REF
      type: string
    - default: HEAD
      description: the revision to sync to
      name: revision
      type: string
    - default: v2.2.2
      name: argocd-version
      type: string
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap
      - secretRef:
          name: argocd-env-secret
    name: ""
    resources: {}
  steps:
    - image: "quay.io/argoproj/argocd:$(params.argocd-version)"
      name: login
      resources: {}
      script: |
        #!/usr/bin/env bash

        set -x

        IFS="/" read -a branchref <<< "$(params.GIT_BRANCH_REF)"
        BRANCH="${branchref[-1]}"
        APP="$(params.APP_NAME)-$BRANCH"

        argocd login "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD" --insecure

        argocd app sync "$APP" --revision "$(params.revision)"

        #argocd app wait "$APP" --health
