kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: default-devsecops-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "devsecops-config"
      server: "*"
  sourceRepos:
    - "*"
status: {}
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: build-pipeline
  namespace: openshift-gitops
spec:
  project: default-devsecops-project
  revisionHistoryLimit: 3
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  destination:
    namespace: devsecops-config
    server: https://kubernetes.default.svc
  source:
    directory:
      recurse: true
    path: pipelines/build
    repoURL: https://github.com/redhat-capgemini-exchange/devsecops-config
    targetRevision: main
--- 
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: rollout-pipeline
  namespace: openshift-gitops
spec:
  project: default-devsecops-project
  revisionHistoryLimit: 3
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  destination:
    namespace: devsecops-config
    server: https://kubernetes.default.svc
  source:
    directory:
      recurse: true
    path: pipelines/rollout
    repoURL: https://github.com/redhat-capgemini-exchange/devsecops-config
    targetRevision: main
