kind: ClusterTask
apiVersion: tekton.dev/v1beta1
metadata:
  name: argocd-sync-app
spec:
  params:
    - name: APP_NAME
      type: string
      description: name of the application to sync    
    - name: GIT_REVISION
      type: string
      default: HEAD
      description: the revision to sync to
    - name: argocd-version
      type: string
      default: v2.2.2
      
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap
      - secretRef:
          name: argocd-env-secret
    name: ""
    resources: {}
  steps:
    - image: "quay.io/argoproj/argocd:$(params.argocd-version)"
      name: login
      resources: {}
      script: |
        #!/usr/bin/env bash

        set -x

        argocd login "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD" --insecure

        argocd app sync "$(params.APP_NAME)-main" --revision "$(params.GIT_REVISION)"

        argocd app sync "$(params.APP_NAME)-release" --revision "$(params.GIT_REVISION)"

        #argocd app wait "$APP" --health
