apiVersion: v1
kind: List
items:
  - kind: AppProject
    apiVersion: argoproj.io/v1alpha1
    metadata:
      name: default-app-project
      namespace: openshift-gitops
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - namespace: '*'
          server: '*'
      sourceRepos:
        - '*'
    status: {}

  - kind: Application
    apiVersion: argoproj.io/v1alpha1
    metadata:
      name: app-infra-config
      namespace: openshift-gitops
    spec:
      project: default-app-project
      revisionHistoryLimit: 3
      destination:
        namespace: '*'
        server: https://kubernetes.default.svc
      source:
        directory:
          recurse: true
        path: cluster
        repoURL: https://github.com/redhat-capgemini-exchange/nodejs-rest-http-crud-gitops
        targetRevision: main
