kind: ClusterTask
apiVersion: tekton.dev/v1beta1
metadata:
  name: tag-deployment-config
spec:
  params:
    - name: APP_NAME
      type: string
    - name: GIT_REVISION
      type: string
    - name: NAMESPACE
      type: string

  steps:
    - name: tag-image
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash

        echo "adding label to deployment config $(params.APP_NAME)"

        oc label dc $(params.APP_NAME) rev=$(params.GIT_REVISION) --overwrite -n $(params.NAMESPACE)